make_file_id: use pageId for generating file ID if possible
OCR-D/core pull request #860
Opened 2022-05-13 16:47 UTC by kba

Implements #825

2022-05-16 09:26 UTC, bertsky requested changes
This does not address the issue, though: If you run on an already existing fileGrp, regardless of `--overwrite` or not, you will get new file IDs (for the same pageId) which will be henceforth be ignored (in the default `skip` strategy of `Processor.input_files`).

See #861 for a different (if unfinished) attempt.

But we probably also have to enforce this _outside_ of `make_file_id`, probably in `Workspace.add_file`: When adding a PAGE-XML file for a pageId that already exists in that fileGrp,
- if `overwrite`, then re-use that fileId
- otherwise raise an exception

2022-05-16 09:26 UTC, bertsky commented on ocrd_utils/ocrd_utils/str.py
> +        if ocrd_file.pageId:
```suggestion
        elif ocrd_file.pageId:
```

2022-10-21 11:25 UTC, bertsky commented
So can this be closed @kba?

2022-10-21 11:31 UTC, kba commented
> So can this be closed @kba?

Yes, I just merged #861

2022-10-21 11:31 UTC, closed without merging