bulk-add: Improve deriving file_id from other fields
OCR-D/core pull request #943
Opened 2022-11-02 16:38 UTC by kba

As raised in #922, if `--file-id` is not provided explicitly, `bulk-add` derived it from the `safe_filename(file_path)` and this had three problems:

* `safe_filename` allowed only a subset of ASCII, now all Unicode letters and digits
* `file_id` was derived from `file_path` even when the "file_path" was actually CSV data. Now it either derives it from `file_path` if it is an actual filepath or from the `srcpath` if not. 
* Derived `file_id` did not follow the convention of starting with the `file_grp`. It does now and also only uses the basename of either `file_path` or `srcpath`

2022-11-02 23:54 UTC, bertsky requested changes
We're nearly there, see suggestions.

Also: the help text for `--file-id` should get something like `If not provided, guess from filename`, too.

2022-11-02 23:54 UTC, bertsky commented on ocrd/ocrd/cli/workspace.py
> +                    # replacements have happened
We forgot to do the same for `--mimetype`. It is currently auto-filled above based on `file_path.suffix`, which is wrong. It should be `srcpath.suffix` below.

```suggestion
                elif param_name in ['mimetype', 'file_id']:
                    # auto-filled below once the other
                    # replacements have happened
```

2022-11-02 23:54 UTC, bertsky commented on ocrd/ocrd/cli/workspace.py
>          if not file_dict['mimetype']:
Should be deleted here (see below).

2022-11-02 23:54 UTC, bertsky commented on ocrd/ocrd/cli/workspace.py
> +
```suggestion
        if not mimetype:
            try:
                file_dict['mimetype'] = EXT_TO_MIME[srcpath.suffix]
            except KeyError:
                log.error("Cannot guess MIME type from extension '%s' for '%s'. Set --mimetype explicitly" % (srcpath.suffix, srcpath))

```

2022-11-03 11:41 UTC, kba commented on ocrd/ocrd/cli/workspace.py
> +            id_field = srcpath.name if file_path != srcpath else file_path.name
Good point. So `.stem` rather than `.name`.

2022-11-03 11:58 UTC, kba commented on ocrd/ocrd/cli/workspace.py
> +            id_field = srcpath.name if file_path != srcpath else file_path.name
a4a7ab3fb

2022-11-03 11:59 UTC, kba commented on ocrd/ocrd/cli/workspace.py
>          if not file_dict['mimetype']:
958a7f9a0

2022-11-03 14:03 UTC, bertsky approved these changes
Thanks!

2022-11-03 14:04 UTC, bertsky commented
> Also: the help text for `--file-id` should get something like `If not provided, guess from filename`, too.

That's on L221 BTW

2022-11-03 15:51 UTC, kba commented
> > Also: the help text for `--file-id` should get something like `If not provided, guess from filename`, too.
> 
> That's on L221 BTW

Added in 4de1cdc0b, thanks for being thorough!

2022-11-09 10:27 UTC, merged